spring:
  application:
    name: ribbon-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck.enabled: true
  instance:
    instance-id: ${spring.application.name}
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

#management.endpoints.jmx.exposure.include: health,info, metrics
management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: User probe as a Ribbon server
  description: This is a netflix ribbon server probe from 5GTANGO VnV Labs
  version: 1.0.0

ribbon-client:
  ribbon:
#    eureka.enabled: true
    eureka.enabled: false
    listOfServers: localhost:9090,localhost:9091,localhost:9092
    ServerListRefreshInterval: 15000

server:
  port: 8888