server:
  port: 8761

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 100
