spring:
  application:
    name: ribbon-client
  profiles:
    active: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck.enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

#management.endpoints.jmx.exposure.include: health,info, metrics
management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Ribbon client probe
  description: This is a netflix ribbon client probe from 5GTANGO VnV Labs
  version: 1.0.0